### ISSUE TITLE
[feat/EPIC-172-ceo] CEO 정보 구현

### ISSUE THREAD

**Issue by MoonInbae** [STUDIO-EYE/STUDIO-EYE-PROMOTIONPAGE-SERVER#10]
## 📄 이슈 내용 

일반 사용자는 CEO 정보(이름, 소개, 이미지)를 조회할 수 있다.
직원은 CEO 정보를 수정, 삭제할 수 있다.

## 📑 상세 내용

일반 사용자는 CEO 정보(이름, 소개, 이미지)를 조회할 수 있다.
직원은 CEO 정보를 수정, 삭제할 수 있다.

## ✔ 체크리스트

- [x] CEO 정보 구조 생성
- [x] CEO 정보(이름, 소개, 이미지) Entity 생성
- [x] CEO 정보 retrieve 구현
- [x] CEO 정보 create 구현
- [x] CEO 정보 update 구현
- [x] CEO 정보 delete구현

## 📍 Reference

-
