### ISSUE TITLE
[feat/EPIC-190-companyInformation] 회사 정보 구현

### ISSUE THREAD

**Issue by MoonInbae** [STUDIO-EYE/STUDIO-EYE-PROMOTIONPAGE-SERVER#11]
## 📄 이슈 내용 

직원은 회사 기본 정보를 수정, 삭제할 수 있다.
직원은 회사 소개 정보를 수정, 삭제할 수 있다.
직원은 5가지 회사 상세 정보를 수정, 삭제할 수 있다.

## 📑 상세 내용

직원은 회사 기본 정보를 수정, 삭제할 수 있다.
직원은 회사 소개 정보를 수정, 삭제할 수 있다.
직원은 5가지 회사 상세 정보를 수정, 삭제할 수 있다.

## ✔ 체크리스트

- [x] 회사 기본 정보 update 구현
- [x] 회사 기본 정보 delete구현
- [x] 회사 소개 정보 update 구현
- [x] 회사 소개 정보 delete구현
- [x] 5가지 회사 상세 정보 update 구현
- [x] 5가지 회사 상세 정보 delete구현

## 📍 Reference

-
