### ISSUE TITLE
[feat/EPIC-212-partnerInformation] 협력사 정보 구현

### ISSUE THREAD

**Issue by MoonInbae** [STUDIO-EYE/STUDIO-EYE-PROMOTIONPAGE-SERVER#13]
## 📄 이슈 내용 
협력사 정보 수정 api 구현

## 📑 상세 내용

협력사 정보 수정 api 구현
partner api에 이름 컬럼 추가
partner 페이지네이션 처리

## ✔ 체크리스트

- [x] 협력사 전체 정보 수정 api 구현 
- [x] partner api에 이름 컬럼 추가
- [x] partner pagination
- [x] retrieve 시에 이름 컬럼 적용
- [x] create 시에 null이면 false로 저장

## 📍 Reference

-
