### ISSUE TITLE
[feat/EPIC-212-companyInformation] 직원 회사 정보 구현

### ISSUE THREAD

**Issue by MoonInbae** [STUDIO-EYE/STUDIO-EYE-PROMOTIONPAGE-SERVER#15]
## 📄 이슈 내용 

직원은 회사 기본 정보를 수정, 삭제할 수 있다.
직원은 회사 소개 정보를 수정, 삭제할 수 있다.
직원은 5가지 회사 상세 정보를 수정, 삭제할 수 있다.
회사 영문 주소 추가 필요

## 📑 상세 내용

직원은 회사 기본 정보를 수정, 삭제할 수 있다.
직원은 회사 소개 정보를 수정, 삭제할 수 있다.
직원은 5가지 회사 상세 정보를 수정, 삭제할 수 있다.
회사 영문 주소 추가 필요
company slogan 이미지 수정 api 추가 필요
company logo, slogan 이미지 모두 수정 api 추가 필요
company introduction 수정 api추가 (main overview, commitment, introduction) 필요

## ✔ 체크리스트

- [x] 회사 기본 정보 update 구현
- [x] 회사 기본 정보 delete구현
- [x] 회사 소개 정보 update 구현
- [x] 회사 소개 정보 delete구현
- [x] 5가지 회사 상세 정보 update 구현
- [x] 5가지 회사 상세 정보 delete구현
- [x] 회사 영문 주소 칼럼 추가
- [x] 회사 영문 주소 칼럼 적용
- [x] company slogan 이미지 수정 api 추가
- [x] company logo, slogan 이미지 모두 수정 api 추가
- [x] company introduction 수정 api추가 (main overview, commitment, introduction)
- [x] 회사 기본정보 조회에서 회사 영문 주소 칼럼 적용
- [x] company introduction 데이터 타입 Text로 변경 (main overview, commitment, introduction)

## 📍 Reference

-
