### ISSUE TITLE
[refactor/EPIC-239-sonarProm] 소나큐브에서 프로모션 서버 코드의 Issues 개수가 줄어든 것을 확인한다.

### ISSUE THREAD

**Issue by MoonInbae** [STUDIO-EYE/STUDIO-EYE-PROMOTIONPAGE-SERVER#18]
## 📄 이슈 내용 

소나큐브에서 프로모션 서버 코드의 Issues 개수가 줄어든 것을 확인한다.

## 📑 상세 내용

소나큐브에서 프로모션 서버 코드의 Issues 개수가 줄어든 것을 확인한다.

## ✔ 체크리스트

- [x] CEO 소나큐브에서 프로모션 서버 코드의 Issues 개수가 줄어든 것을 확인한다.
- [x] Views 소나큐브에서 프로모션 서버 코드의 Issues 개수가 줄어든 것을 확인한다.
- [x] CompanyInformation 소나큐브에서 프로모션 서버 코드의 Issues 개수가 줄어든 것을 확인한다.
- [x] Email 소나큐브에서 프로모션 서버 코드의 Issues 개수가 줄어든 것을 확인한다.
- [x] FAQ 소나큐브에서 프로모션 서버 코드의 Issues 개수가 줄어든 것을 확인한다.

## 📍 Reference

-
