### ISSUE TITLE
[feat/EPIC-172-client] 고객사(client) 정보 기능 구현

### ISSUE THREAD

**Issue by MoonInbae** [STUDIO-EYE/STUDIO-EYE-PROMOTIONPAGE-SERVER#19]
## 📄 이슈 내용 

client 공개여부 추가
client 페이지네이션 처리

## 📑 상세 내용

client 공개여부 추가
client 페이지네이션 처리

## ✔ 체크리스트

- [x] client 공개여부 추가
- [x] client pagination
- [x] Retrieve 시에 client 공개여부 추가
- [x] create 시에 null이면 false로 저장

## 📍 Reference

-
