### ISSUE TITLE
[feat/EPIC-245-recruitment] 채용공고 게시판 기능 구현

### ISSUE THREAD

**Issue by MoonInbae** [STUDIO-EYE/STUDIO-EYE-PROMOTIONPAGE-SERVER#22]
## 📄 이슈 내용 

홍보 관리자는 관리 페이지의 채용공고 게시판에서 게시글을 작성, 수정, 삭제할 수 있다.
사용자는 홍보 페이지에서 채용공고 게시글을 확인할 수 있다.

## 📑 상세 내용

게시 글 작성, 조회, 수정, 삭제 기능
채용공고 엔티티 구성(제목, 기간, 자격요건, 우대요건)
PP에서는 제일 최신 공고만 띄우기 PA는 전부 띄우기

## ✔ 체크리스트

- [x] 채용공고 게시물 Entity(id, title, content) 생성
- [x] 채용공고 게시물 CRUD 구현
- [x] 채용공고 게시물 목록 Retrieve api 구현
- [x] 채용공고 게시물 목록 Pagination
- [x] 채용공고 엔티티 수정(제목, 시작일, 마감일, 상태, 링크, 생성일, 자격요건, 우대요건)
- [x] PP 채용공고 Retrieve api 구현
- [x] 상태 자동 변경 기능 구현

## 📍 Reference

-
