### ISSUE TITLE
[feat/EPIC-260-companyInformation] 버전별 로고 조회

### ISSUE THREAD

**Issue by MoonInbae** [STUDIO-EYE/STUDIO-EYE-PROMOTIONPAGE-SERVER#45]
## 📄 이슈 내용 

light/dark 버전 로고 조회

## 📑 상세 내용

light/dark 버전 로고 조회

## ✔ 체크리스트

- [x] 기존의 logoImageUrl, logoImageFileName을 lightLogoImageUrl, lightLogoImageFileName, darkLogoImageUrl, DarkLogoImageFileName로 엔티티 구조 수정
- [x] 기존의 로고 조회 api를 boolean 값에 따른 light/dark 버전 로고 조회 기능 조회 api로 수정
- [x] 기존의 회사 정보 등록 API에 로고 등록 방식 수정
- [x] 기존의 회사 로고 이미지 수정 API에 로고 수정 방식 수정
- [x] 기존의 회사 로고 이미지 삭제 API에 로고 삭제 방식 수정

## 📍 Reference

-
