### ISSUE TITLE
[feat/EPIC-260-project] 프로젝트 반응형 이미지 구현

### ISSUE THREAD

**Issue by MoonInbae** [STUDIO-EYE/STUDIO-EYE-PROMOTIONPAGE-SERVER#50]
## 📄 이슈 내용 

프로젝트 main image 반응형 이미지 구현

## 📑 상세 내용

프로젝트 main image가 반응형 기기(모바일)에서 절반 잘린 사진으로 표시가 되어 반응형 이미지를 따로 저장하여 반응형 기기에서는 반응형 이미지를 사용하도록 구현

## ✔ 체크리스트

- [x] Project Entity에 responsiveMainImg 추가
- [x] Project 생성 API 반응형 이미지 적용
- [x] Project 조회 API 반응형 이미지 적용
- [x] Project 수정 API 반응형 이미지 적용
- [x] Project 삭제 API 반응형 이미지 적용

## 📍 Reference

-
