### ISSUE TITLE
[feat/EPIC-103-mail] 프로모션 페이지의 문의(의뢰) 상태 구현

### ISSUE THREAD

**Issue by MoonInbae** [STUDIO-EYE/STUDIO-EYE-PROMOTIONPAGE-SERVER#7]
## 📄 이슈 내용 

직원의 의뢰 승인, 거부 설정에 따라 고객에게 승인, 거부 메일을 보낸다.

## 📑 상세 내용

직원의 의뢰 승인, 거부 설정에 따라 고객에게 승인, 거부 메일을 보낸다.
대기중, 승인, 거부, 처리완료

## ✔ 체크리스트

- [X] 상태 칼럼 추가
- [x] 문의 추가 시 상태를 대기중으로 등록
- [x] 문의 답변 등록 시, 문의 상태도 함께 변경할 수 있도록 처리
- [x] 문의 상태 변경 api 생성

## 📍 Reference

-
