### ISSUE TITLE
[feat/EPIC-172-companyInformation] 일반 사용자 회사 정보 구현

### ISSUE THREAD

**Issue by MoonInbae** [STUDIO-EYE/STUDIO-EYE-PROMOTIONPAGE-SERVER#9]
## 📄 이슈 내용 

일반 사용자는 회사 기본 정보를 조회할 수 있다.
일반 사용자는 회사 소개 정보를 조회할 수 있다.
일반 사용자는 5가지 회사 상세 정보를 조회할 수 있다.

## 📑 상세 내용

일반 사용자는 회사 기본 정보를 조회할 수 있다.
일반 사용자는 회사 소개 정보를 조회할 수 있다.
일반 사용자는 5가지 회사 상세 정보를 조회할 수 있다.

## ✔ 체크리스트

- [x] 회사 정보 구조 생성
- [x] 회사 정보(회사 기본 정보, 회사 소개 정보, 회사 상세 정보 통합) Entity 생성
- [x] 회사 기본 정보 retrieve 구현
- [x] 회사 소개 정보 retrieve 구현
- [x] 5가지 회사 상세 정보 retrieve 구현

## 📍 Reference

-
